platform: nsync futex: fix build on riscv32 (#18)
RISCV glibc has decided to use 64bit time_t from get go unlike
other 32bit architecture therefore aliasing __NR_futex to
__NR_futex_time64 helps avoid the below errors on rv32

error: '__NR_futex' was not declared in this scope
|    21 |         return (syscall (__NR_futex, uaddr, op, val, timeout, uaddr2, val3));
|       |